# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlineStore' do
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~>3.8'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OnlineStore

  target 'OnlineStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnlineStoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
